sudo: required
services:
  - docker

before_install:
  - docker build -t autosapien/cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true autosapien/cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "cicd-docker-travis"
  env: "CicdDockerTravis-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-823692275467"
  bucket_path: "cicd-docker-travis"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
